[2024-03-11T22:01:56.646+0000] {processor.py:161} INFO - Started process (PID=39) to work on /opt/airflow/dags/airflow.py
[2024-03-11T22:01:56.656+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2024-03-11T22:01:56.668+0000] {logging_mixin.py:188} INFO - [2024-03-11T22:01:56.667+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2024-03-11T22:02:01.221+0000] {logging_mixin.py:188} INFO - [2024-03-11T22:02:01.219+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 14, in <module>
    from src.outlier_handle import handle_outliers
  File "/opt/airflow/dags/src/outlier_handle.py", line 3, in <module>
    from sklearn.ensemble import IsolationForest
ModuleNotFoundError: No module named 'sklearn'
[2024-03-11T22:02:01.221+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2024-03-11T22:02:01.249+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow.py took 4.804 seconds
[2024-03-11T22:02:32.087+0000] {processor.py:161} INFO - Started process (PID=104) to work on /opt/airflow/dags/airflow.py
[2024-03-11T22:02:32.090+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2024-03-11T22:02:32.092+0000] {logging_mixin.py:188} INFO - [2024-03-11T22:02:32.091+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2024-03-11T22:02:32.709+0000] {logging_mixin.py:188} INFO - [2024-03-11T22:02:32.707+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 14, in <module>
    from src.outlier_handle import handle_outliers
  File "/opt/airflow/dags/src/outlier_handle.py", line 3, in <module>
    from sklearn.ensemble import IsolationForest
ModuleNotFoundError: No module named 'sklearn'
[2024-03-11T22:02:32.709+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2024-03-11T22:02:32.744+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow.py took 0.660 seconds
[2024-03-11T22:03:03.521+0000] {processor.py:161} INFO - Started process (PID=162) to work on /opt/airflow/dags/airflow.py
[2024-03-11T22:03:03.523+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2024-03-11T22:03:03.524+0000] {logging_mixin.py:188} INFO - [2024-03-11T22:03:03.524+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2024-03-11T22:03:03.810+0000] {logging_mixin.py:188} INFO - [2024-03-11T22:03:03.807+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 14, in <module>
    from src.outlier_handle import handle_outliers
  File "/opt/airflow/dags/src/outlier_handle.py", line 3, in <module>
    from sklearn.ensemble import IsolationForest
ModuleNotFoundError: No module named 'sklearn'
[2024-03-11T22:03:03.810+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2024-03-11T22:03:03.833+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow.py took 0.315 seconds
[2024-03-11T22:05:11.911+0000] {processor.py:161} INFO - Started process (PID=38) to work on /opt/airflow/dags/airflow.py
[2024-03-11T22:05:11.913+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2024-03-11T22:05:11.916+0000] {logging_mixin.py:188} INFO - [2024-03-11T22:05:11.916+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2024-03-11T22:05:12.716+0000] {logging_mixin.py:188} INFO - [2024-03-11T22:05:12.711+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 14, in <module>
    from src.outlier_handle import handle_outliers
  File "/opt/airflow/dags/src/outlier_handle.py", line 3, in <module>
    from sklearn.ensemble import IsolationForest
ModuleNotFoundError: No module named 'sklearn'
[2024-03-11T22:05:12.716+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2024-03-11T22:05:12.753+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow.py took 0.848 seconds
[2024-03-11T22:05:42.894+0000] {processor.py:161} INFO - Started process (PID=95) to work on /opt/airflow/dags/airflow.py
[2024-03-11T22:05:42.896+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2024-03-11T22:05:42.899+0000] {logging_mixin.py:188} INFO - [2024-03-11T22:05:42.899+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2024-03-11T22:05:43.279+0000] {logging_mixin.py:188} INFO - [2024-03-11T22:05:43.277+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 14, in <module>
    from src.outlier_handle import handle_outliers
  File "/opt/airflow/dags/src/outlier_handle.py", line 3, in <module>
    from sklearn.ensemble import IsolationForest
ModuleNotFoundError: No module named 'sklearn'
[2024-03-11T22:05:43.279+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2024-03-11T22:05:43.315+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow.py took 0.425 seconds
[2024-03-11T22:06:13.413+0000] {processor.py:161} INFO - Started process (PID=152) to work on /opt/airflow/dags/airflow.py
[2024-03-11T22:06:13.415+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2024-03-11T22:06:13.420+0000] {logging_mixin.py:188} INFO - [2024-03-11T22:06:13.419+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2024-03-11T22:06:13.752+0000] {logging_mixin.py:188} INFO - [2024-03-11T22:06:13.750+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 14, in <module>
    from src.outlier_handle import handle_outliers
  File "/opt/airflow/dags/src/outlier_handle.py", line 3, in <module>
    from sklearn.ensemble import IsolationForest
ModuleNotFoundError: No module named 'sklearn'
[2024-03-11T22:06:13.753+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2024-03-11T22:06:13.784+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow.py took 0.377 seconds
[2024-03-11T22:06:43.904+0000] {processor.py:161} INFO - Started process (PID=211) to work on /opt/airflow/dags/airflow.py
[2024-03-11T22:06:43.905+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2024-03-11T22:06:43.907+0000] {logging_mixin.py:188} INFO - [2024-03-11T22:06:43.906+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2024-03-11T22:06:44.195+0000] {logging_mixin.py:188} INFO - [2024-03-11T22:06:44.194+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 14, in <module>
    from src.outlier_handle import handle_outliers
  File "/opt/airflow/dags/src/outlier_handle.py", line 3, in <module>
    from sklearn.ensemble import IsolationForest
ModuleNotFoundError: No module named 'sklearn'
[2024-03-11T22:06:44.195+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2024-03-11T22:06:44.217+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow.py took 0.316 seconds
[2024-03-11T22:07:15.148+0000] {processor.py:161} INFO - Started process (PID=269) to work on /opt/airflow/dags/airflow.py
[2024-03-11T22:07:15.150+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2024-03-11T22:07:15.151+0000] {logging_mixin.py:188} INFO - [2024-03-11T22:07:15.151+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2024-03-11T22:07:15.395+0000] {logging_mixin.py:188} INFO - [2024-03-11T22:07:15.394+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 14, in <module>
    from src.outlier_handle import handle_outliers
  File "/opt/airflow/dags/src/outlier_handle.py", line 3, in <module>
    from sklearn.ensemble import IsolationForest
ModuleNotFoundError: No module named 'sklearn'
[2024-03-11T22:07:15.396+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2024-03-11T22:07:15.418+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow.py took 0.273 seconds
[2024-03-11T22:07:45.635+0000] {processor.py:161} INFO - Started process (PID=327) to work on /opt/airflow/dags/airflow.py
[2024-03-11T22:07:45.636+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2024-03-11T22:07:45.638+0000] {logging_mixin.py:188} INFO - [2024-03-11T22:07:45.637+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2024-03-11T22:07:45.879+0000] {logging_mixin.py:188} INFO - [2024-03-11T22:07:45.878+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 14, in <module>
    from src.outlier_handle import handle_outliers
  File "/opt/airflow/dags/src/outlier_handle.py", line 3, in <module>
    from sklearn.ensemble import IsolationForest
ModuleNotFoundError: No module named 'sklearn'
[2024-03-11T22:07:45.879+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2024-03-11T22:07:45.901+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow.py took 0.269 seconds
[2024-03-11T22:08:16.018+0000] {processor.py:161} INFO - Started process (PID=384) to work on /opt/airflow/dags/airflow.py
[2024-03-11T22:08:16.020+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2024-03-11T22:08:16.022+0000] {logging_mixin.py:188} INFO - [2024-03-11T22:08:16.021+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2024-03-11T22:08:16.742+0000] {logging_mixin.py:188} INFO - [2024-03-11T22:08:16.739+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 14, in <module>
    from src.outlier_handle import handle_outliers
  File "/opt/airflow/dags/src/outlier_handle.py", line 3, in <module>
    from sklearn.ensemble import IsolationForest
ModuleNotFoundError: No module named 'sklearn'
[2024-03-11T22:08:16.742+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2024-03-11T22:08:16.792+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow.py took 0.777 seconds
[2024-03-11T22:08:47.429+0000] {processor.py:161} INFO - Started process (PID=442) to work on /opt/airflow/dags/airflow.py
[2024-03-11T22:08:47.431+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2024-03-11T22:08:47.433+0000] {logging_mixin.py:188} INFO - [2024-03-11T22:08:47.433+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2024-03-11T22:08:47.706+0000] {logging_mixin.py:188} INFO - [2024-03-11T22:08:47.705+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 14, in <module>
    from src.outlier_handle import handle_outliers
  File "/opt/airflow/dags/src/outlier_handle.py", line 3, in <module>
    from sklearn.ensemble import IsolationForest
ModuleNotFoundError: No module named 'sklearn'
[2024-03-11T22:08:47.707+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2024-03-11T22:08:47.730+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow.py took 0.304 seconds
[2024-03-11T22:09:18.426+0000] {processor.py:161} INFO - Started process (PID=499) to work on /opt/airflow/dags/airflow.py
[2024-03-11T22:09:18.459+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2024-03-11T22:09:18.460+0000] {logging_mixin.py:188} INFO - [2024-03-11T22:09:18.460+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2024-03-11T22:09:18.708+0000] {logging_mixin.py:188} INFO - [2024-03-11T22:09:18.707+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 14, in <module>
    from src.outlier_handle import handle_outliers
  File "/opt/airflow/dags/src/outlier_handle.py", line 3, in <module>
    from sklearn.ensemble import IsolationForest
ModuleNotFoundError: No module named 'sklearn'
[2024-03-11T22:09:18.708+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2024-03-11T22:09:18.730+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow.py took 0.307 seconds
[2024-03-11T22:09:48.752+0000] {processor.py:161} INFO - Started process (PID=556) to work on /opt/airflow/dags/airflow.py
[2024-03-11T22:09:48.753+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2024-03-11T22:09:48.755+0000] {logging_mixin.py:188} INFO - [2024-03-11T22:09:48.754+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2024-03-11T22:09:49.007+0000] {logging_mixin.py:188} INFO - [2024-03-11T22:09:49.006+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 14, in <module>
    from src.outlier_handle import handle_outliers
  File "/opt/airflow/dags/src/outlier_handle.py", line 3, in <module>
    from sklearn.ensemble import IsolationForest
ModuleNotFoundError: No module named 'sklearn'
[2024-03-11T22:09:49.007+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2024-03-11T22:09:49.027+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow.py took 0.279 seconds
[2024-03-11T22:10:19.070+0000] {processor.py:161} INFO - Started process (PID=613) to work on /opt/airflow/dags/airflow.py
[2024-03-11T22:10:19.072+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2024-03-11T22:10:19.075+0000] {logging_mixin.py:188} INFO - [2024-03-11T22:10:19.074+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2024-03-11T22:10:19.350+0000] {logging_mixin.py:188} INFO - [2024-03-11T22:10:19.348+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 14, in <module>
    from src.outlier_handle import handle_outliers
  File "/opt/airflow/dags/src/outlier_handle.py", line 3, in <module>
    from sklearn.ensemble import IsolationForest
ModuleNotFoundError: No module named 'sklearn'
[2024-03-11T22:10:19.350+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2024-03-11T22:10:19.372+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow.py took 0.305 seconds
[2024-03-11T22:10:49.412+0000] {processor.py:161} INFO - Started process (PID=670) to work on /opt/airflow/dags/airflow.py
[2024-03-11T22:10:49.414+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2024-03-11T22:10:49.415+0000] {logging_mixin.py:188} INFO - [2024-03-11T22:10:49.415+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2024-03-11T22:10:49.985+0000] {logging_mixin.py:188} INFO - [2024-03-11T22:10:49.984+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 14, in <module>
    from src.outlier_handle import handle_outliers
  File "/opt/airflow/dags/src/outlier_handle.py", line 3, in <module>
    from sklearn.ensemble import IsolationForest
ModuleNotFoundError: No module named 'sklearn'
[2024-03-11T22:10:49.985+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2024-03-11T22:10:50.006+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow.py took 0.597 seconds
[2024-03-11T22:11:20.280+0000] {processor.py:161} INFO - Started process (PID=726) to work on /opt/airflow/dags/airflow.py
[2024-03-11T22:11:20.299+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2024-03-11T22:11:20.301+0000] {logging_mixin.py:188} INFO - [2024-03-11T22:11:20.300+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2024-03-11T22:11:20.609+0000] {logging_mixin.py:188} INFO - [2024-03-11T22:11:20.608+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 14, in <module>
    from src.outlier_handle import handle_outliers
  File "/opt/airflow/dags/src/outlier_handle.py", line 3, in <module>
    from sklearn.ensemble import IsolationForest
ModuleNotFoundError: No module named 'sklearn'
[2024-03-11T22:11:20.610+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2024-03-11T22:11:20.629+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow.py took 0.352 seconds
[2024-03-11T22:11:51.140+0000] {processor.py:161} INFO - Started process (PID=783) to work on /opt/airflow/dags/airflow.py
[2024-03-11T22:11:51.143+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2024-03-11T22:11:51.145+0000] {logging_mixin.py:188} INFO - [2024-03-11T22:11:51.145+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2024-03-11T22:11:51.499+0000] {logging_mixin.py:188} INFO - [2024-03-11T22:11:51.497+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 14, in <module>
    from src.outlier_handle import handle_outliers
  File "/opt/airflow/dags/src/outlier_handle.py", line 3, in <module>
    from sklearn.ensemble import IsolationForest
ModuleNotFoundError: No module named 'sklearn'
[2024-03-11T22:11:51.499+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2024-03-11T22:11:51.527+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow.py took 0.391 seconds
[2024-03-11T22:12:22.362+0000] {processor.py:161} INFO - Started process (PID=840) to work on /opt/airflow/dags/airflow.py
[2024-03-11T22:12:22.364+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2024-03-11T22:12:22.366+0000] {logging_mixin.py:188} INFO - [2024-03-11T22:12:22.365+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2024-03-11T22:12:22.840+0000] {logging_mixin.py:188} INFO - [2024-03-11T22:12:22.838+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 14, in <module>
    from src.outlier_handle import handle_outliers
  File "/opt/airflow/dags/src/outlier_handle.py", line 3, in <module>
    from sklearn.ensemble import IsolationForest
ModuleNotFoundError: No module named 'sklearn'
[2024-03-11T22:12:22.841+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2024-03-11T22:12:22.864+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow.py took 0.505 seconds
[2024-03-11T22:12:53.021+0000] {processor.py:161} INFO - Started process (PID=898) to work on /opt/airflow/dags/airflow.py
[2024-03-11T22:12:53.023+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2024-03-11T22:12:53.025+0000] {logging_mixin.py:188} INFO - [2024-03-11T22:12:53.025+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2024-03-11T22:12:53.619+0000] {logging_mixin.py:188} INFO - [2024-03-11T22:12:53.617+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 14, in <module>
    from src.outlier_handle import handle_outliers
  File "/opt/airflow/dags/src/outlier_handle.py", line 3, in <module>
    from sklearn.ensemble import IsolationForest
ModuleNotFoundError: No module named 'sklearn'
[2024-03-11T22:12:53.620+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2024-03-11T22:12:53.642+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow.py took 0.625 seconds
[2024-03-11T22:13:23.675+0000] {processor.py:161} INFO - Started process (PID=958) to work on /opt/airflow/dags/airflow.py
[2024-03-11T22:13:23.677+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2024-03-11T22:13:23.682+0000] {logging_mixin.py:188} INFO - [2024-03-11T22:13:23.681+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2024-03-11T22:13:24.293+0000] {logging_mixin.py:188} INFO - [2024-03-11T22:13:24.292+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 14, in <module>
    from src.outlier_handle import handle_outliers
  File "/opt/airflow/dags/src/outlier_handle.py", line 3, in <module>
    from sklearn.ensemble import IsolationForest
ModuleNotFoundError: No module named 'sklearn'
[2024-03-11T22:13:24.294+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2024-03-11T22:13:24.361+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow.py took 0.689 seconds
[2024-03-11T22:13:54.996+0000] {processor.py:161} INFO - Started process (PID=1015) to work on /opt/airflow/dags/airflow.py
[2024-03-11T22:13:54.998+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2024-03-11T22:13:55.000+0000] {logging_mixin.py:188} INFO - [2024-03-11T22:13:55.000+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2024-03-11T22:13:55.392+0000] {logging_mixin.py:188} INFO - [2024-03-11T22:13:55.391+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 14, in <module>
    from src.outlier_handle import handle_outliers
  File "/opt/airflow/dags/src/outlier_handle.py", line 3, in <module>
    from sklearn.ensemble import IsolationForest
ModuleNotFoundError: No module named 'sklearn'
[2024-03-11T22:13:55.392+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2024-03-11T22:13:55.412+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow.py took 0.418 seconds
[2024-03-11T22:14:25.509+0000] {processor.py:161} INFO - Started process (PID=1076) to work on /opt/airflow/dags/airflow.py
[2024-03-11T22:14:25.511+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2024-03-11T22:14:25.513+0000] {logging_mixin.py:188} INFO - [2024-03-11T22:14:25.512+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2024-03-11T22:14:25.878+0000] {logging_mixin.py:188} INFO - [2024-03-11T22:14:25.877+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 14, in <module>
    from src.outlier_handle import handle_outliers
  File "/opt/airflow/dags/src/outlier_handle.py", line 3, in <module>
    from sklearn.ensemble import IsolationForest
ModuleNotFoundError: No module named 'sklearn'
[2024-03-11T22:14:25.878+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2024-03-11T22:14:25.898+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow.py took 0.391 seconds
[2024-03-11T22:14:56.712+0000] {processor.py:161} INFO - Started process (PID=1135) to work on /opt/airflow/dags/airflow.py
[2024-03-11T22:14:56.714+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2024-03-11T22:14:56.716+0000] {logging_mixin.py:188} INFO - [2024-03-11T22:14:56.716+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2024-03-11T22:14:57.168+0000] {logging_mixin.py:188} INFO - [2024-03-11T22:14:57.167+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 14, in <module>
    from src.outlier_handle import handle_outliers
  File "/opt/airflow/dags/src/outlier_handle.py", line 3, in <module>
    from sklearn.ensemble import IsolationForest
ModuleNotFoundError: No module named 'sklearn'
[2024-03-11T22:14:57.168+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2024-03-11T22:14:57.196+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow.py took 0.486 seconds
[2024-03-11T22:15:28.132+0000] {processor.py:161} INFO - Started process (PID=1195) to work on /opt/airflow/dags/airflow.py
[2024-03-11T22:15:28.134+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2024-03-11T22:15:28.135+0000] {logging_mixin.py:188} INFO - [2024-03-11T22:15:28.135+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2024-03-11T22:15:28.537+0000] {logging_mixin.py:188} INFO - [2024-03-11T22:15:28.536+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 14, in <module>
    from src.outlier_handle import handle_outliers
  File "/opt/airflow/dags/src/outlier_handle.py", line 3, in <module>
    from sklearn.ensemble import IsolationForest
ModuleNotFoundError: No module named 'sklearn'
[2024-03-11T22:15:28.538+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2024-03-11T22:15:28.558+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow.py took 0.428 seconds
[2024-03-11T22:15:58.588+0000] {processor.py:161} INFO - Started process (PID=1255) to work on /opt/airflow/dags/airflow.py
[2024-03-11T22:15:58.589+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2024-03-11T22:15:58.591+0000] {logging_mixin.py:188} INFO - [2024-03-11T22:15:58.590+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2024-03-11T22:15:58.996+0000] {logging_mixin.py:188} INFO - [2024-03-11T22:15:58.995+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 14, in <module>
    from src.outlier_handle import handle_outliers
  File "/opt/airflow/dags/src/outlier_handle.py", line 3, in <module>
    from sklearn.ensemble import IsolationForest
ModuleNotFoundError: No module named 'sklearn'
[2024-03-11T22:15:58.996+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2024-03-11T22:15:59.018+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow.py took 0.434 seconds
[2024-03-11T22:16:29.055+0000] {processor.py:161} INFO - Started process (PID=1315) to work on /opt/airflow/dags/airflow.py
[2024-03-11T22:16:29.057+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2024-03-11T22:16:29.061+0000] {logging_mixin.py:188} INFO - [2024-03-11T22:16:29.060+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2024-03-11T22:16:29.532+0000] {logging_mixin.py:188} INFO - [2024-03-11T22:16:29.531+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 14, in <module>
    from src.outlier_handle import handle_outliers
  File "/opt/airflow/dags/src/outlier_handle.py", line 3, in <module>
    from sklearn.ensemble import IsolationForest
ModuleNotFoundError: No module named 'sklearn'
[2024-03-11T22:16:29.532+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2024-03-11T22:16:29.558+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow.py took 0.507 seconds
[2024-03-11T22:16:59.624+0000] {processor.py:161} INFO - Started process (PID=1375) to work on /opt/airflow/dags/airflow.py
[2024-03-11T22:16:59.626+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2024-03-11T22:16:59.627+0000] {logging_mixin.py:188} INFO - [2024-03-11T22:16:59.627+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2024-03-11T22:17:00.035+0000] {logging_mixin.py:188} INFO - [2024-03-11T22:17:00.034+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 14, in <module>
    from src.outlier_handle import handle_outliers
  File "/opt/airflow/dags/src/outlier_handle.py", line 3, in <module>
    from sklearn.ensemble import IsolationForest
ModuleNotFoundError: No module named 'sklearn'
[2024-03-11T22:17:00.035+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2024-03-11T22:17:00.054+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow.py took 0.432 seconds
